#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-accounts', '8.0.0'
mod 'HEPPuppet-htcondor',
  :git => 'https://github.com/mickaneda/htcondor'
mod 'mickaneda-files',
  :git => 'https://github.com/mickaneda/puppet-files'
mod 'mickaneda-google_fluentd',
  :git => 'https://github.com/mickaneda/puppet-google_fluentd'
